### ISSUE TITLE
things... todo... eventually...

### ISSUE THREAD

**Issue by ronduma** [ronduma/cs545-project#1]
Multiple Choice
- [ ] randomized musical notes
- [ ] ensure one of the notes is the correct note, and that there are no repeating choices
- [ ] if the user selects an incorrect choice, the button is greyed out
